v1_user_controller:
    resource: '../src/Manager/User/Infrastructure/Controller/V1/'
    type: attribute
    prefix: /api

v1_task_controller:
    resource: '../src/Manager/Task/Infrastructure/Controller/V1/'
    type: attribute
    prefix: /api
